### ISSUE TITLE
Remove package-lock.json from the project

### ISSUE THREAD

**Issue by mickeymond** [mickeymond/ecommerce-app-beta#2]
1. Delete package-lock.json
2. Add the following lines of code to the .gitignore file.

```
package-lock.json
yarn.lock
```
Ensure you work from a branch created from develop and raise a PR into develop..

**Comment by pualine** [comment]
Tracy you are taking too much time working on this, please speed up!

**Comment by Besiwahfors** [comment]
Tracyyyyyyy we are waiting
